#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --architectures amd64 \
    --debian-installer false \
    --archive-areas "main" \
    --apt-indices false \
    --memtest none \
    "${@}"

